# NumPy Tutorial

Shouvik Mani <br>
September 24, 2021 <br>
COMS 4995: Applied Machine Learning, Columbia University

In [1]:
import numpy as np

### 1. Creating Vectors and Matrices

Create a vector.

In [2]:
x = np.array([1, 2, 3, 4, 5])

print(x.shape)
print(x)

(5,)
[1 2 3 4 5]


Create a matrix.

In [3]:
A = np.array([[2, 1, 4], 
              [5, 0, 1], 
              [3, 2, 1]])
              
print(A.shape)
print(A)

(3, 3)
[[2 1 4]
 [5 0 1]
 [3 2 1]]


Special matrices

In [4]:
np.zeros(shape=(3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones(shape=(4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# Identity matrix
np.eye(N=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Evenly spaced numbers

In [7]:
# 11 numbers between 0 and 1
x = np.linspace(start=0, stop=1, num=11)

print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


Sample random numbers from a Normal distribution. There are many more distributions you can choose from (see documentation for np.random).

In [8]:
# Seed the random number generator (important for reproducible results)
np.random.seed(1)

# Sample from a Normal distribution with mean 0 and standard deviation 1
x = np.random.normal(loc=0, scale=1, size=5)

print(x)

[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763]


In [9]:
# Sample from a Uniform distribution
np.random.uniform(low=0, high=1, size=10)

array([0.41919451, 0.6852195 , 0.20445225, 0.87811744, 0.02738759,
       0.67046751, 0.4173048 , 0.55868983, 0.14038694, 0.19810149])

### 2. Indexing, Slicing, and Iterating

In [10]:
A = np.array([[2, 1, 4], 
              [5, 0, 1], 
              [3, 2, 1]])

Access an element by index

In [11]:
A[2]   # Index into row 2

array([3, 2, 1])

In [12]:
A[2, 2]   # Index into row 2, column 2

1

Set a value at an index

In [13]:
A[2, 2] = -1
print(A)

[[ 2  1  4]
 [ 5  0  1]
 [ 3  2 -1]]


Slicing

In [14]:
# Slice rows 0 through 1, cols 1 through 2
A[0:2, 1:3]

array([[1, 4],
       [0, 1]])

In [15]:
# Slice all rows, col 0
A[:, 0]

array([2, 5, 3])

Iterating over a matrix

In [16]:
# Iterating over rows
for row in A:
    print(row)

[2 1 4]
[5 0 1]
[ 3  2 -1]


In [17]:
sum = 0

# Iterating over rows and cols
for row in A:
    for elem in row:
        sum += elem
        
print(sum)

17


### 3. Basic Vector and Matrix Operations

Scalar multiplication and vector addition

In [18]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 0, 1, 0, 1])

print(2 * x + y)

[ 3  4  7  8 11]


Dot product

In [19]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 0, 1, 0, 1])

# Two different ways!
print(x @ y)
print(x.dot(y))

9
9


Vector norm

In [20]:
x = np.array([1, 2, 3, 4, 5])

print(np.linalg.norm(x, 1))   # L1-norm
print(np.linalg.norm(x, 2))   # L2-norm (i.e. vector magnitude)

15.0
7.416198487095663


Matrix transpose

In [21]:
A = np.array([[2, 1, 4], 
              [5, 0, 1], 
              [3, 2, 1]])

print(A.T)

[[2 5 3]
 [1 0 2]
 [4 1 1]]


Reshape a matrix

In [22]:
A = np.array([[2, 1, 4], 
              [5, 0, 1]])
a = A.reshape((6, 1))

print(a)

[[2]
 [1]
 [4]
 [5]
 [0]
 [1]]


Scalar multiplication and matrix addition

In [23]:
A = np.array([[2, 1, 4], 
              [5, 0, 1], 
              [3, 2, 1]])
B = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

print(2 * A + B)

[[ 5  4 11]
 [14  5  8]
 [13 12 11]]


Elementwise multiplication (**not matrix multiplication**)

In [24]:
print(A * B)

[[ 2  2 12]
 [20  0  6]
 [21 16  9]]


Matrix multiplication

In [25]:
# Two different ways!
print(A @ B)
print()
print(A.dot(B))

[[34 41 48]
 [12 18 24]
 [18 24 30]]

[[34 41 48]
 [12 18 24]
 [18 24 30]]


Matrix inverse

In [26]:
A = np.array([[3, 1], 
              [1, 3]])
A_inv = np.linalg.inv(A)

print(A_inv)

[[ 0.375 -0.125]
 [-0.125  0.375]]


In [27]:
A @ A_inv

array([[1., 0.],
       [0., 1.]])

Stacking matrices

In [28]:
A = np.array([[2, 1, 4], 
              [5, 0, 1]])
B = np.array([[1, 2, 3], 
              [4, 5, 6]])

In [29]:
np.hstack([A, B])

array([[2, 1, 4, 1, 2, 3],
       [5, 0, 1, 4, 5, 6]])

In [30]:
np.vstack([A, B])

array([[2, 1, 4],
       [5, 0, 1],
       [1, 2, 3],
       [4, 5, 6]])

Element-wise functions (e.g. np.log, np.exp, np.sqrt)

In [31]:
A = np.array([[1, 4, 9], 
              [16, 25, 36], 
              [49, 64, 81]])

np.sqrt(A)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

Aggregate functions (e.g. np.mean, np.std, np.sum)

In [32]:
A = np.array([[1, 1, 1], 
              [2, 2, 2], 
              [3, 3, 3]])

print(A.sum())          # Sum of all elements in A
print(A.sum(axis=0))    # Sum of each column in A
print(A.sum(axis=1))    # Sum of each row in A

18
[6 6 6]
[3 6 9]


### 4. Solving Systems of Linear Equations

Consider the following system of linear equations:

$$
\begin{aligned}
3a + b &= 5 \\
a - 5b &= 7
\end{aligned}
$$

We can rewrite this as the equation $A x = b$, where $A$ and $b$ are defined as follows.

In [33]:
A = np.array([[3, 1], 
              [1, -5]])
b = np.array([5, 7])

Then, we can solve for an exact solution $x$.

In [34]:
# Find an exact solution x for A x = b
x = np.linalg.solve(A, b)
x

array([ 2., -1.])

This is the same as $x = A^{-1} b$. But `np.linalg.solve(A, b)` is the preferred method because it does not explicitly solve for the inverse, which is an expensive operation.

In [35]:
x = np.linalg.inv(A) @ b
x

array([ 2., -1.])

What happens when $A$ is not a square matrix? For example, consider the following 
(overdetermined) system of linear equations:

$$
\begin{aligned}
3a + b &= 5 \\
a - 5b &= 7 \\
a + b &= 0
\end{aligned}
$$


In [36]:
A = np.array([[3, 1], 
              [1, -5], 
              [1, 1]])
b = np.array([5, 7, 0])

We can't use `np.linalg.solve(A, b)` since A is not square, i.e. not invertible.

In [37]:
# Does not work - A not invertible
x = np.linalg.solve(A, b)
x

LinAlgError: Last 2 dimensions of the array must be square

Instead, we can find a least squares approximate solution for $x$.

In [38]:
# Find an approximate solution x for A x = b using least squares.
x, resid, rank, s = np.linalg.lstsq(A, b)
x

<ipython-input-38-a23de93341b9>:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, resid, rank, s = np.linalg.lstsq(A, b)


array([ 1.90540541, -1.04054054])

Estimates for $b$ using least squares approx. for $x$.

In [39]:
A @ x

array([4.67567568, 7.10810811, 0.86486486])

Compare estimates above with the actual $b$.

In [40]:
b

array([5, 7, 0])

### 5. Broadcasting

Consider the following matrix $A$.

In [41]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])

print(A)

[[1 2 3]
 [4 5 6]]


Imagine that you want to add 2 to each element of the matrix above. One way to do it is the following.

In [42]:
B = np.array([[2, 2, 2], 
              [2, 2, 2]])

A + B

array([[3, 4, 5],
       [6, 7, 8]])

However, a cleaner way to write this would be `A + 2`. This is a NumPy feature known as **broadcasting**, which automatically resizes arrays in the most natural way to perform an operation.

In [43]:
A + 2

array([[3, 4, 5],
       [6, 7, 8]])

Broadcasting can be applied in interesting ways. Here, we subtract off the mean from each column of A. This works even though A has dimension (2, 3) and the means have dimension (3,).

In [45]:
means = A.mean(axis=0)
means

array([2.5, 3.5, 4.5])

In [47]:
print("Dimension of A:", A.shape)
print("Dimension of means:", means.shape)

A - means

Dimension of A: (2, 3)
Dimension of means: (3,)


array([[-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5]])

### 6. Vectorization

One of the key principles when using NumPy is to *vectorize your code*. Vectorizing your code means to favor matrix/vector operations over for-loops. Vectorizing code has two main benefits:
- Vectorized code uses optimized NumPy operations, which makes it faster.
- Vectorized code is cleaner and easier to read than code with for-loops.

Next, we consider two examples of writing vectorized code.

### Example 1: Standardization

Transform the matrix $X$ so that each column is scaled to have a mean of 0 and variance of 1.

In [48]:
X = np.random.normal(loc=10, scale=5, size=(1000000, 5))
print(X.shape)
X

(1000000, 5)


array([[-1.50769348, 15.66884721,  4.50054366,  9.13785896,  5.61070791],
       [10.21106873, 12.91407607,  4.49690411, 15.72361855, 14.5079536 ],
       [12.51247169, 14.50427975,  6.5813607 ,  9.38554887,  5.32115283],
       ...,
       [15.80126225, 14.89656129,  5.04754566,  9.62357914,  8.44210443],
       [13.92708984,  8.16450725,  8.66912362,  6.2033972 , 10.89750732],
       [ 6.23914075,  4.21336079, 14.02342302,  8.01400123, 10.51294067]])

#### Method 1: Using for-loops (bad!)

In [49]:
X_ = []

for col in X.T:
    col_mean = col.mean()
    col_std_dev = col.std()
    col_standardized = []
    for elem in col:
        elem_standardized = (elem - col_mean) / col_std_dev
        col_standardized.append(elem_standardized)
    X_.append(col_standardized)
    
X_ = np.array(X_).T

In [50]:
X_

array([[-2.30493741,  1.13471421, -1.09909553, -0.17265984, -0.87570179],
       [ 0.04112746,  0.58322643, -1.09982304,  1.14553058,  0.90313329],
       [ 0.50186218,  0.90157516, -0.68316168, -0.1230828 , -0.93359282],
       ...,
       [ 1.16026926,  0.98010745, -0.98975548, -0.07543921, -0.3096179 ],
       [ 0.78506495, -0.36760723, -0.26583942, -0.76001492,  0.18129322],
       [-0.7540419 , -1.15860178,  0.80442976, -0.3976086 ,  0.10440643]])

In [51]:
X_.mean(axis=0)

array([-5.45263390e-16, -9.43796152e-16, -2.13606910e-16, -6.23774810e-16,
        9.32317334e-16])

In [52]:
X_.std(axis=0)

array([1., 1., 1., 1., 1.])

#### Method 2: Vectorized (good!)

In [53]:
means = X.mean(axis=0)
std_devs = X.std(axis=0)
X_ = (X - means) / std_devs

In [54]:
X_.mean(axis=0)

array([-4.80382056e-15, -9.83738246e-15, -4.92025274e-14,  9.93416408e-14,
        1.24516596e-13])

In [55]:
X_.std(axis=0)

array([1., 1., 1., 1., 1.])

### Example 2: Calculating distances

Consider a matrix $X$ in which each row is a data point. Compute a vector of distances $d$ between a query point $q$ and each row in $X$.

In [56]:
X = np.random.normal(loc=10, scale=5, size=(1000000, 5))

print(X.shape)
print("X:", X)

q = np.random.normal(loc=10, scale=5, size=(5))
print()
print("q:", q)

(1000000, 5)
X: [[ 9.30833775 10.42248806 10.52938601 11.05451163 18.644658  ]
 [ 5.01984283 11.96819984  7.72789213 21.53361797  9.10897265]
 [ 1.9297422  -0.19131274 11.3580658   4.73502151  8.9277174 ]
 ...
 [ 6.46975441  6.51146122  7.17997652 13.50106152 -3.29922082]
 [17.32224476  4.87503224 15.32022013 12.5488937  16.92537832]
 [ 7.33168374  5.30299988 15.72761558  8.72139542  3.02936306]]

q: [ 6.12940979 10.35748247 13.07030433  1.13200145 10.46370174]


#### Method 1: Using for-loops (bad!)

This code works, but it's ugly and takes a long time to run.

In [57]:
d = []

for x in X:
    sum_squared_diffs = 0
    for i in range(5):
        squared_diff = (x[i] - q[i]) ** 2
        sum_squared_diffs += squared_diff
    distance_x_to_q = sum_squared_diffs ** (1/2)
    d.append(distance_x_to_q)

d = np.array(d)
print(d.shape)
d

(1000000,)


array([13.48889647, 21.22329298, 12.13206704, ..., 19.79937777,
       18.23451752, 12.12117372])

#### Method 2: Vectorized (good!)

We can write vectorized code that's clean and fast!

In [63]:
d = ((X - q) ** 2).sum(axis=1) ** (1/2)

print(d.shape)
d

(1000000,)


array([13.48889647, 21.22329298, 12.13206704, ..., 19.79937777,
       18.23451752, 12.12117372])